name: Run tests

on:
  pull_request:
    branches: [ dev, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install npm packages
        run: npm ci

      - name: Run Angular build
        run: npm run build

      - name: Run Angular tests
        run: npm test -- --watch=false